version: "3.7"

services:
  app:
    # Docker context https://stackoverflow.com/questions/37099008/docker-compose-build-error-when-using-parent-dir-dockerfile-for-build
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    depends_on: 
      - db
    ports:
      - 8085:8085
    environment:
      DB_CONN_URL: postgres://postgres:postgres@db/accounts-db
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - 9001:5432
    volumes:
      - ./container-data/db:/var/lib/postgresql/data:rw
  cache:
    image: redis:alpine