version: '2.4'

services:
  jenkins:
    build: ./jenkins
    volumes:
      - ./ci-pipeline-data/jenkins_data:/var/jenkins_home
    environment:
      - JENKINS_USER=admin
      - JENKINS_PASS=admin
    ports:
      - 8080:8080

volumes:
  jenkins_data:
