version: '2.4'

services:
  jenkins:
    build: ./jenkins
    volumes:
      - ./ci-pipeline-data/jenkins_data:/var/jenkins_home
    environment:
      - SONARQUBE_URL=http://localhost:9000
      - JENKINS_USER=admin
      - JENKINS_PASS=admin
    ports:
      - 8080:8080
    depends_on:
      - sonarqube

  sonarqube:
    # Changed from latest to 7.9.3-community so it could run on Macs
    image: sonarqube:7.9.3-community
    privileged: true
    volumes:
      - ./ci-pipeline-data/sonarqube_conf:/opt/sonarqube/conf
      - ./ci-pipeline-data/sonarqube_data:/opt/sonarqube/data
      - ./ci-pipeline-data/sonarqube_logs:/opt/sonarqube/logs
      - ./ci-pipeline-data/sonarqube_extensions:/opt/sonarqube/extensions
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://postgres/sonar
    ports:
      - 9000:9000
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:11-alpine
    volumes:
      - ./ci-pipeline-data/postgresql:/var/lib/postgresql
      - ./ci-pipeline-data/postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonar"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  jenkins_data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  postgresql:
  postgresql_data:
