version: "3.7"
services: 
    db: 
        image: postgres
        environment: 
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: medical-conditions-db
        volumes: 
            - ./pgdata:/var/lib/postgresql/data
        build:
            dockerfile: ./db/Dockerfile
        ports:
            - '5432:5432'
    web:
        image: medical-conditions-web
        depends_on: 
            - db
        ports: 
            - '8080:8080'
        volumes:
            - .:/usr/src/app
