version: "3.3"
services: 
    bookings-db:
        image: "muhammadw123/bookings-db" 
        container_name: postgres-bookings
        environment: 
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: bookings_db
        volumes: 
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - '8083:5432'
    bookings-web:
        image: 'muhammadw123/bookings-web'
        depends_on: 
            - db
        ports: 
            - '8081:8081'
        restart: always
