version: "3.3"
services: 
    db: 
        container_name: postgres-bookings
        environment: 
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: bookings_db
        volumes: 
            - ./pgdata:/var/lib/postgresql/data
        build:
            context: .
            dockerfile: ./db/Dockerfile
        ports:
            - '8083:5432'
    web:
        image: bookings-web
        depends_on: 
            - db
        ports: 
            - '8081:8081'
        restart: always
        command: npm start
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
