apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o kompose-factory
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: inventory-db
  name: inventory-db
spec:
  ports:
  - name: "5436"
    port: 5436
    targetPort: 5432
  selector:
    io.kompose.service: inventory-db
status:
  loadBalancer: {}
