apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o kompose-factory
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: inventory-web
  name: inventory-web
spec:
  ports:
  - name: "8085"
    port: 8085
    targetPort: 8080
  selector:
    io.kompose.service: inventory-web
status:
  loadBalancer: {}
